//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWebinarSample.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_990_01_EBOOKDETAILDOC
    {
        public int LOGICALREF { get; set; }
        public Nullable<int> EMFICHEREF { get; set; }
        public Nullable<short> DOCUMENTTYPE { get; set; }
        public string EXPLAIN { get; set; }
        public string DOCUMENTNR { get; set; }
        public Nullable<System.DateTime> DOCUMENTDATE { get; set; }
        public string PAYTYPE { get; set; }
        public Nullable<short> UNDOCUMENTED { get; set; }
        public Nullable<short> NOPAYMENT { get; set; }
        public Nullable<int> EMFLINEREF { get; set; }
        public Nullable<short> MODULENR { get; set; }
        public Nullable<int> SOURCEFREF { get; set; }
    }
}
