//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWebinarSample.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_990_01_EMFLINE
    {
        public int LOGICALREF { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<short> SIGN { get; set; }
        public Nullable<int> ACCOUNTREF { get; set; }
        public Nullable<int> ACCFICHEREF { get; set; }
        public Nullable<int> CENTERREF { get; set; }
        public Nullable<short> TRCODE { get; set; }
        public Nullable<short> BRANCH { get; set; }
        public string KEBIRCODE { get; set; }
        public string ACCOUNTCODE { get; set; }
        public string SPECODE { get; set; }
        public Nullable<double> DEBIT { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public Nullable<short> LINENO_ { get; set; }
        public string LINEEXP { get; set; }
        public Nullable<short> CANCELLED { get; set; }
        public Nullable<short> TRCURR { get; set; }
        public Nullable<short> CURRDIFFCALC { get; set; }
        public Nullable<double> REPORTRATE { get; set; }
        public Nullable<double> REPORTNET { get; set; }
        public Nullable<double> TRRATE { get; set; }
        public Nullable<double> TRNET { get; set; }
        public Nullable<double> AMNT { get; set; }
        public Nullable<int> EXTENREF { get; set; }
        public Nullable<double> EMUDEBIT { get; set; }
        public Nullable<double> EMUCREDIT { get; set; }
        public Nullable<short> LINEEXCTYP { get; set; }
        public string CROSSCODE { get; set; }
        public Nullable<short> SITEID { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<int> ORGLOGICREF { get; set; }
        public Nullable<double> INFIDX { get; set; }
        public Nullable<short> NOTINFLATED { get; set; }
        public Nullable<short> NOTCALCULATED { get; set; }
        public Nullable<short> FROMWHERE { get; set; }
        public Nullable<int> OWNERACCREF { get; set; }
        public Nullable<short> DEPARTMENT { get; set; }
        public Nullable<short> BDGTLINETYPE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> BDGTFCTYPE { get; set; }
        public Nullable<int> BDGTFCREF { get; set; }
        public Nullable<int> BDGTFCLNREF { get; set; }
        public Nullable<int> BDGTFCPRDREF { get; set; }
        public Nullable<short> FROMDEMTYPE { get; set; }
        public Nullable<int> EMDEMFCREF { get; set; }
        public Nullable<int> EMDEMLNREF { get; set; }
        public Nullable<int> PARENTLNREF { get; set; }
        public Nullable<double> PAIDTOTAL { get; set; }
        public Nullable<short> CLOSED { get; set; }
        public Nullable<short> OUTFCTYPE { get; set; }
        public Nullable<int> OUTFCREF { get; set; }
        public Nullable<short> CREATEBDGTLN { get; set; }
        public Nullable<short> MONTH_ { get; set; }
        public Nullable<short> YEAR_ { get; set; }
        public Nullable<short> GRPFIRMTRANS { get; set; }
        public string INVOICENO { get; set; }
        public string CLDEF { get; set; }
        public string TAXNR { get; set; }
        public Nullable<short> FORTAXDECL { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public Nullable<int> UFRSLNREF { get; set; }
        public Nullable<double> UFRSNETAMNT { get; set; }
        public Nullable<int> GLOBLINENO { get; set; }
        public Nullable<short> LINETYPE { get; set; }
        public Nullable<int> CODEREF { get; set; }
        public string SPECODE2 { get; set; }
        public Nullable<int> SOURCEFREF { get; set; }
        public string GUID { get; set; }
        public string CLCODE { get; set; }
        public Nullable<int> SOURCEFLNREF { get; set; }
        public Nullable<int> DISTTEMPREF { get; set; }
        public Nullable<int> PROJECTREF { get; set; }
        public string TCKNO { get; set; }
        public Nullable<short> CASHLINE { get; set; }
        public Nullable<short> MNTHLINE { get; set; }
        public Nullable<int> MNTHSOURCEREF { get; set; }
        public Nullable<short> MNTHCOUNT { get; set; }
        public Nullable<short> ELECTDOC { get; set; }
    }
}
