//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWebinarSample.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_990_01_EMFICHE
    {
        public int LOGICALREF { get; set; }
        public Nullable<short> TRCODE { get; set; }
        public string FICHENO { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
        public string DOCODE { get; set; }
        public Nullable<short> BRANCH { get; set; }
        public Nullable<short> DEPARTMENT { get; set; }
        public Nullable<short> MODULENO { get; set; }
        public Nullable<int> SOURCEFREF { get; set; }
        public Nullable<int> EXTENREF { get; set; }
        public string GENEXP1 { get; set; }
        public string GENEXP2 { get; set; }
        public string GENEXP3 { get; set; }
        public string GENEXP4 { get; set; }
        public string GENEXP5 { get; set; }
        public string GENEXP6 { get; set; }
        public Nullable<int> JOURNALNO { get; set; }
        public Nullable<double> TOTALACTIVE { get; set; }
        public Nullable<double> TOTALPASSIVE { get; set; }
        public Nullable<short> CANCELLED { get; set; }
        public Nullable<short> PRINTCNT { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDSEC { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDSEC { get; set; }
        public Nullable<short> MODULENR { get; set; }
        public Nullable<int> CANCFREF { get; set; }
        public Nullable<double> EMUTOTACTIVE { get; set; }
        public Nullable<double> EMUTOTPASSIVE { get; set; }
        public Nullable<short> GENEXCTYP { get; set; }
        public Nullable<short> LINEEXCTYP { get; set; }
        public Nullable<short> SITEID { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<int> ORGLOGICALREF { get; set; }
        public Nullable<double> REPTOTACTIVE { get; set; }
        public Nullable<double> REPTOTPASSIVE { get; set; }
        public Nullable<short> TEXTINC { get; set; }
        public Nullable<int> WFSTATUS { get; set; }
        public Nullable<int> CROSSFREF { get; set; }
        public Nullable<short> CROSSFLAG { get; set; }
        public Nullable<short> DOCTYPE { get; set; }
        public string ORGLOGOID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> BDGTFCTYPE { get; set; }
        public Nullable<int> BDGTFCREF { get; set; }
        public Nullable<short> FROMDEMTYPE { get; set; }
        public Nullable<int> EMDEMFCREF { get; set; }
        public Nullable<int> WFLOWCRDREF { get; set; }
        public Nullable<short> VIAAUTOGL { get; set; }
        public Nullable<short> APPROVE { get; set; }
        public Nullable<System.DateTime> APPROVEDATE { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public Nullable<short> BATCHTYPE { get; set; }
        public string GUID { get; set; }
        public Nullable<short> LINEBASEDDOCDET { get; set; }
        public Nullable<short> ISIMPDISTFC { get; set; }
        public Nullable<System.DateTime> PRINTDATE { get; set; }
        public Nullable<int> PROJECTREF { get; set; }
        public Nullable<System.DateTime> PERSBEGDATE { get; set; }
        public Nullable<System.DateTime> PERSENDDATE { get; set; }
        public string RECHASH { get; set; }
        public Nullable<short> CONTROLINFO { get; set; }
        public Nullable<int> NOTIFYCRDREF { get; set; }
    }
}
