//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWebinarSample.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_990_EMUHACC
    {
        public int LOGICALREF { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public string CODE { get; set; }
        public string DEFINITION_ { get; set; }
        public string EXTNAME { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
        public string UNITS { get; set; }
        public Nullable<int> ADDINFOPTR { get; set; }
        public Nullable<int> CENTERREF { get; set; }
        public Nullable<int> CURRDIFREF { get; set; }
        public Nullable<int> SUBACCOUNTS { get; set; }
        public Nullable<short> LEVEL_ { get; set; }
        public Nullable<short> GROUPCODE { get; set; }
        public Nullable<short> ACCTYPE { get; set; }
        public Nullable<short> QUANCTRL { get; set; }
        public Nullable<short> CENTERCTRL { get; set; }
        public Nullable<int> EXTENREF { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDSEC { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDSEC { get; set; }
        public Nullable<short> SITEID { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<int> ORGLOGICALREF { get; set; }
        public Nullable<int> WFSTATUS { get; set; }
        public Nullable<short> POSTINGONLY { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public string FTFLAGS { get; set; }
        public Nullable<short> MONETARY { get; set; }
        public Nullable<short> PROJECTCTRL { get; set; }
        public Nullable<short> NOTINFLATED { get; set; }
        public Nullable<int> CURRDIFFDEBTREF { get; set; }
        public Nullable<int> INFDIFFACCREF { get; set; }
        public Nullable<short> ISANBDGTLINE { get; set; }
        public Nullable<int> BDGTACCREF { get; set; }
        public Nullable<int> BDREFLACCREF { get; set; }
        public Nullable<int> BDGTPAYAREF { get; set; }
        public Nullable<int> BDPAYREFLAREF { get; set; }
        public Nullable<short> CRBDGTACCLN { get; set; }
        public Nullable<short> CRBDGTPAYALN { get; set; }
        public string CORPCODE1 { get; set; }
        public string CORPCODE2 { get; set; }
        public string CORPCODE3 { get; set; }
        public string CORPCODE4 { get; set; }
        public string FUNCCODE1 { get; set; }
        public string FUNCCODE2 { get; set; }
        public string FUNCCODE3 { get; set; }
        public string FUNCCODE4 { get; set; }
        public string FINCODE { get; set; }
        public string ECOCODE1 { get; set; }
        public string ECOCODE2 { get; set; }
        public string ECOCODE3 { get; set; }
        public string ECOCODE4 { get; set; }
        public Nullable<int> VATREFLAREF { get; set; }
        public Nullable<int> VATREFLOTHAREF { get; set; }
        public Nullable<short> CCURRENCY { get; set; }
        public Nullable<short> CURRATETYPE { get; set; }
        public Nullable<short> FIXEDCURRTYPE { get; set; }
        public string CLDEF { get; set; }
        public string TAXNR { get; set; }
        public Nullable<short> FORTAXDECL { get; set; }
        public Nullable<short> VATACC { get; set; }
        public Nullable<int> GRPTRANSACCREF { get; set; }
        public string SPECODE2 { get; set; }
        public string SPECODE3 { get; set; }
        public string SPECODE4 { get; set; }
        public string SPECODE5 { get; set; }
        public string TCKNO { get; set; }
        public Nullable<short> ISPERSCOMP { get; set; }
        public Nullable<short> ISCASH { get; set; }
        public Nullable<short> TEXTINC { get; set; }
        public Nullable<short> TEXTINCENG { get; set; }
    }
}
